### PR TITLE
Update README.md file with more detail

### PR DESCRIPTION
**Pull request by sgilda**

### CODE REVIEW

**Comment by sgilda** [comment]
@emmartins : I tried out the tool and it worked great! I made some changes to the README file if you are interested. At some point we need to talk so I know what the plans are for this going forward.

**Comment by sgilda** [comment]
@emmartins : I just review the jboss-eap-7.0 directory after running the tool and am a little confused. I no longer see the `standalone/` or `domain/` directory. Instead, I also don't see the `docs/` or `modules/` directories. Instead, I see  a lot of new subdirectories for all of the subsystems.

**Comment by emmartins** [comment]
@sgilda what should I do with this PR?

**Comment by sgilda** [comment]
@emmartins : Sorry! I made the updates after my comment. This can be merged if you approve of the changes!

**Comment by sgilda** [comment]
@emmartins : I do have one question. If you run the tool more than once against the same configuration, you lose the original backup configuration file, correct? Do you plan to add a unique identifier to the file name so the backup does not get lost? If not, we may want to add a warning about this issue.

**Comment by sgilda** [comment]
I was hoping you might want to merge this back into your repository for others who are trying to test it out. :-)

**Pull request closed without merging**
